# Cloud Run deployment configuration

steps:
  # Build backend image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/url-shortener-backend:$COMMIT_SHA'
      - './backend'
    dir: '.'

  # Push backend image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/url-shortener-backend:$COMMIT_SHA'

  # Build frontend image  
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/url-shortener-frontend:$COMMIT_SHA'
      - './frontend'
    dir: '.'

  # Push frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/url-shortener-frontend:$COMMIT_SHA'

  # Deploy backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'url-shortener-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/url-shortener-backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'ENVIRONMENT=production'
      - '--set-secrets'
      - 'SECRET_KEY=secret-key:latest'
      - '--set-secrets'
      - 'DATABASE_URL=database-url:latest'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1000m'
      - '--max-instances'
      - '10'

  # Deploy frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'url-shortener-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/url-shortener-frontend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--memory'
      - '256Mi'
      - '--cpu'
      - '1000m'
      - '--max-instances'
      - '5'

images:
  - 'gcr.io/$PROJECT_ID/url-shortener-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/url-shortener-frontend:$COMMIT_SHA'