steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'gcr.io/$PROJECT_ID/url-changer:$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/url-changer:latest',
      '.'
    ]

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/url-changer:$COMMIT_SHA']

  # Push the latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/url-changer:latest']

  # Deploy to Cloud Run (environment variables already set in Cloud Run service)
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'url-changer',
      '--image', 'gcr.io/$PROJECT_ID/url-changer:$COMMIT_SHA',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]

images:
  - 'gcr.io/$PROJECT_ID/url-changer:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/url-changer:latest'