version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - ENVIRONMENT=production
      - DATABASE_URL=postgresql://username:password@db:5432/urlchanger
      - SECRET_KEY=${SECRET_KEY}
      - DOMAIN=${DOMAIN}
      - BASE_URL=https://${DOMAIN}
      - API_KEY=${API_KEY}
      - ALLOWED_ORIGINS=https://${DOMAIN},https://www.${DOMAIN}
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - VITE_API_BASE_URL=https://${DOMAIN}
      - VITE_API_KEY=${API_KEY}
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=urlchanger
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: